[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "graph_solver"
version = "0.1.0"
dependencies = [
    "pyscipopt",
    "torch",
    'torch_geometric',
    'numpy'
]